export const toolbarMenuList = {
    '|': () => import('./components/divider'),
    'undo': () => import('./components/undo'),
    'redo': () => import('./components/redo'),
    'painter': () => import('./components/painter'),
    'format': () => import('./components/format'),
    'font': () => import('./components/font'),
    'size': () => import('./components/size'),
    'sizeAdd': () => import('./components/sizeAdd'),
    'sizeMinus': () => import('./components/sizeMinus'),
    'bold': () => import('./components/bold'),
    'italic': () => import('./components/italic'),
    'underline': () => import('./components/underline'),
    'strikeout': () => import('./components/strikeout'),
    'superscript': () => import('./components/superscript'),
    'subscript': () => import('./components/subscript'),
    'color': () => import('./components/color'),
    'highlight': () => import('./components/highlight'),
    'title': () => import('./components/title'),
    'left': () => import('./components/left'),
    'center': () => import('./components/center'),
    'right': () => import('./components/right'),
    'alignment': () => import('./components/alignment'),
    'justify': () => import('./components/justify'),
    'margin': () => import('./components/margin'),
    'list': () => import('./components/list'),
    'table': () => import('./components/table'),
    'imageUpload': () => import('./components/imageUpload'),
    'hyperlink': () => import('./components/hyperlink'),
    'separator': () => import('./components/separator'),
    'watermark': () => import('./components/watermark'),
    'codeblock': () => import('./components/codeblock'),
    'pageBreak': () => import('./components/pageBreak'),
    'control': () => import('./components/control'),
    'checkbox': () => import('./components/checkbox'),
    'radio': () => import('./components/radio'),
    'latex': () => import('./components/latex'),
    'date': () => import('./components/date'),
    'block': () => import('./components/block'),
    'search': () => import('./components/search'),
    'print': () => import('./components/print'),
};

export const toolbarMenu = [
    [ 'undo', 'redo', 'painter', 'format' ],
    '|',
    [ 'font', 'size', 'sizeAdd', 'sizeMinus', 'bold', 'italic', 'underline', 'strikeout', 'superscript', 'subscript', 'color', 'highlight' ],
    '|',
    [ 'title', 'left', 'center', 'right', 'alignment', 'justify', 'margin', 'list' ],
    '|',
    [ 'table', 'imageUpload', 'hyperlink', 'separator', 'watermark', 'codeblock', 'pageBreak', 'control', 'checkbox', 'radio', 'latex', 'date', 'block' ],
    '|',
    [ 'search', 'print' ]
]